# .readthedocs.yaml
version: 2

# Build tools and environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Python dependencies
python:
  install:
    - requirements: docs/requirements.txt
